version: '3.7'
services:
  react-playground:
    image: react-playground:v1
    ports:
      - 3001:3000
    container_name: react-playground
    restart: always
    volumes:
      - /app/node_modules
      - ./:/app
    environment:
      - WATCHPACK_POLLING=true # its neccessary for run in docker
    
